// automatically generated by the FlatBuffers compiler, do not modify

package Sample

const (
	ParameterTypeFBool = 1
	ParameterTypeFByte = 2
	ParameterTypeFInt = 3
	ParameterTypeFLong = 4
	ParameterTypeFShort = 5
	ParameterTypeFFloat = 6
	ParameterTypeFDouble = 7
	ParameterTypeFString = 8
	ParameterTypeFBuffer = 9
)

var EnumNamesParameterType = map[int]string{
	ParameterTypeFBool:"FBool",
	ParameterTypeFByte:"FByte",
	ParameterTypeFInt:"FInt",
	ParameterTypeFLong:"FLong",
	ParameterTypeFShort:"FShort",
	ParameterTypeFFloat:"FFloat",
	ParameterTypeFDouble:"FDouble",
	ParameterTypeFString:"FString",
	ParameterTypeFBuffer:"FBuffer",
}

