// automatically generated by the FlatBuffers compiler, do not modify

package Sample

const (
	RPCModeServer = 0
	RPCModeOthers = 1
	RPCModeAll = 2
	RPCModeBuffered = 3
)

var EnumNamesRPCMode = map[int]string{
	RPCModeServer:"Server",
	RPCModeOthers:"Others",
	RPCModeAll:"All",
	RPCModeBuffered:"Buffered",
}

