// automatically generated by the FlatBuffers compiler, do not modify

package Sample

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RpcToServer struct {
	_tab flatbuffers.Table
}

func GetRootAsRpcToServer(buf []byte, offset flatbuffers.UOffsetT) *RpcToServer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RpcToServer{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RpcToServer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RpcToServer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RpcToServer) Mode() int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt8(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RpcToServer) MutateMode(n int8) bool {
	return rcv._tab.MutateInt8Slot(4, n)
}

func (rcv *RpcToServer) IsReliable() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RpcToServer) MutateIsReliable(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *RpcToServer) SyncId() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RpcToServer) MutateSyncId(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *RpcToServer) FuncName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcToServer) ParamData(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RpcToServer) ParamDataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RpcToServer) ParamDataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RpcToServer) ParamTypes(j int) int8 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt8(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *RpcToServer) ParamTypesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *RpcToServer) ParamSize(j int) uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetUint16(a + flatbuffers.UOffsetT(j*2))
	}
	return 0
}

func (rcv *RpcToServer) ParamSizeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RpcToServerStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func RpcToServerAddMode(builder *flatbuffers.Builder, mode int8) {
	builder.PrependInt8Slot(0, mode, 0)
}
func RpcToServerAddIsReliable(builder *flatbuffers.Builder, isReliable byte) {
	builder.PrependByteSlot(1, isReliable, 0)
}
func RpcToServerAddSyncId(builder *flatbuffers.Builder, syncId int32) {
	builder.PrependInt32Slot(2, syncId, 0)
}
func RpcToServerAddFuncName(builder *flatbuffers.Builder, funcName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(funcName), 0)
}
func RpcToServerAddParamData(builder *flatbuffers.Builder, paramData flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(paramData), 0)
}
func RpcToServerStartParamDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RpcToServerAddParamTypes(builder *flatbuffers.Builder, paramTypes flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(paramTypes), 0)
}
func RpcToServerStartParamTypesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func RpcToServerAddParamSize(builder *flatbuffers.Builder, paramSize flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(paramSize), 0)
}
func RpcToServerStartParamSizeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(2, numElems, 2)
}
func RpcToServerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
